[project]
name = "elkeep"
version = "0.1.0"
description = "Google Keep interface for Emacs"
requires-python = ">=3.13"
dependencies = [
    "gkeepapi>=0.16.0",
    "keyring>=25.6.0",
    "pypandoc>=1.15",
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
